# Generated by Django 5.0.4 on 2024-04-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Staff'), (4, 'Customer')], default=4, null=True),
        ),
    ]
