# Generated by Django 5.0.4 on 2024-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='default/logo.jpg', upload_to='school_logos/')),
                ('banner', models.ImageField(default='default/school_banner.png', upload_to='banner/')),
            ],
        ),
    ]
