# Generated by Django 5.0.4 on 2024-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='default/logo.png', upload_to='school_logos/'),
        ),
    ]
