# Generated by Django 5.0.4 on 2024-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('flyer', models.ImageField(default='default/flyer.png', upload_to='course_flyers/')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
