# Generated by Django 5.0.4 on 2024-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner', models.ImageField(default='default/default_banner.jpg', upload_to='service_banners/')),
                ('description', models.TextField()),
            ],
        ),
    ]
