# Generated by Django 5.0.4 on 2024-04-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Service_category',
        ),
    ]
