# Generated by Django 5.0.4 on 2024-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='header',
            field=models.ImageField(default='default/default_banner.jpg', upload_to='service_headers/'),
        ),
    ]
