# Generated by Django 5.0.4 on 2024-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_category_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='header',
            field=models.ImageField(default='default/header.png', upload_to='service_headers/'),
        ),
    ]
